env:
  global:
    - secure: e5YPYD8r6oRY0bNVDUzptaRD1rsuj4FkXWMYRjk48OyR6XecsVqyCBgH63o7SyfZ2n9wMcGxiyFJrl4vBsUrj+ZC07pQsQFo/vT6KjCeop1S/fxSOyRGUh9hbN+/vEm/NQ2uKaslo2OHWCHe9vCGtXD8n3p3U6Dn0goORe7S80k=
language: rust
install: sudo apt-get install -qq libvorbis-dev
after_script:
  - cargo doc
  - ln -s target/doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
